Repository gwkokab/gwkokab, pull requests merged in 2025-05, with the labels that each got.

#534 refactor: saving raw injections in population generation
  .pre-commit-config.yaml
  src/gwkokab/population/_factory.py
  uv.lock
Labels: internal

#536 fix: correction in poisson likelihood and saving raw injections
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  src/gwkokab/inference/poissonlikelihood.py
  src/gwkokab/models/transformations.py
  src/gwkokab/models/utils/_scaledmixture.py
  src/gwkokab/poisson_mean.py
  src/gwkokab/population/_factory.py
  uv.lock
Labels: internal, script: genie

#539 docs(gh-107): update synthetic data generation tutorial
  examples/synthetic_data.ipynb
Labels: documentation

#540 docs(gh-107): update analysis by gwkokab notebook
  examples/analysis_by_gwkokab.ipynb
Labels: documentation

#541 docs(gh-107): example for an inference
  examples/analysis_by_gwkokab.ipynb
Labels: documentation

#544 Updated documentation with selection effects from model in fake PE
  .pre-commit-config.yaml
  examples/fake_pe_generation.ipynb
  examples/synthetic_data.ipynb
  pyproject.toml
  src/gwkokab/inference/poissonlikelihood.py
  src/gwkokab/population/_factory.py
  src/kokab/__init__.py
  src/kokab/chi_eff_q_relation/__init__.py
  src/kokab/chi_eff_q_relation/sage.py
  uv.lock
Labels: documentation, internal

#546 refactor(gh-543): remove `constraint` parameter from `PopulationFactory`
  src/gwkokab/population/_factory.py
  src/kokab/ecc_matters/common.py
  src/kokab/ecc_matters/genie.py
  src/kokab/n_spls_m_sgs/common.py
Labels: internal
